### ISSUE TITLE
Unable to set ZSHRCD variable

### ISSUE THREAD

**Issue by jaohaohsuan** [mattmc3/zshrc.d#3]
It always shows `zshrc.d: dir not found ''` whether I set ZSHRCD variable or not.

**Comment by mattmc3** [comment]
I think there's 2 issues here - the first is that this plugin wasn't printing a proper error message and should have said:

```zsh
zshrc.d: dir not found '$ZSHRCD'
```

That issue is fixed.

The second issue is that whatever you set `$ZSHRCD` to doesn't exist. Make sure you `mkdir -p $ZSHRCD`. This plugin will not create the directory for you. This is to prevent littering your filesystem due to typos that would be left to the user to clean up. So, ultimately, the plugin is behaving as expected, but the error message had a bug.
